export const mockJobs = [
    // 1. STATUT: NOUVELLE (5 items)
    {
        ID_Annonce: "WTTJ_001",
        Titre_poste: "Senior React Developer",
        Entreprise: "TechInnovate",
        Lieu: "Paris (Hybride)",
        Type_contrat: "CDI",
        Salaire: "60-75k€",
        URL_offre: "https://example.com/job1",
        URL_Entreprise: "https://techinnovate.io",
        Description: "Nous cherchons un expert React pour leader notre refonte frontend...",
        score_ATS: 92,
        remarque_ATS: "Profil excellent, correspond parfaitement aux exigences techniques. Stack match à 100%.",
        _score_details: "React (+10); Redux (-2); Lead (+5)",
        data_pour_agent_redacteur: null,
        Statut: "Nouvelle",
        Source: "WTTJ",
        Date_Publication: "2023-10-25"
    },
    {
        ID_Annonce: "FT_002",
        Titre_poste: "Développeur Front-End",
        Entreprise: "Agence WebRapid",
        Lieu: "Lyon",
        Type_contrat: "CDI",
        Salaire: "40-50k€",
        URL_offre: "https://example.com/job2",
        URL_Entreprise: "https://webrapid.fr",
        Description: "Agence digitale cherche dev front pour intégration de maquettes...",
        score_ATS: 78,
        remarque_ATS: "Bon profil mais salaire un peu bas par rapport aux attentes.",
        _score_details: "Front (+5); Salaire (-2); Lyon (0)",
        data_pour_agent_redacteur: null,
        Statut: "Nouvelle",
        Source: "FT",
        Date_Publication: "2023-10-24"
    },
    {
        ID_Annonce: "MININT_003",
        Titre_poste: "Ingénieur d'études J2EE",
        Entreprise: "Ministère de l'Intérieur",
        Lieu: "Paris 12e",
        Type_contrat: "CDD 3 ans",
        Salaire: "Non communiqué",
        URL_offre: "https://example.com/job3",
        URL_Entreprise: "https://interieur.gouv.fr",
        Description: "Maintenance et évolution des applications régaliennes...",
        score_ATS: 65,
        remarque_ATS: "Stack Java un peu datée, mais contexte intéressant.",
        _score_details: "Java (+2); Public (+3); CDD (-5)",
        data_pour_agent_redacteur: null,
        Statut: "Nouvelle",
        Source: "MININT",
        Date_Publication: "2023-10-23"
    },
    {
        ID_Annonce: "WTTJ_004",
        Titre_poste: "Fullstack Developer JS",
        Entreprise: "StartupX",
        Lieu: "Remote",
        Type_contrat: "Freelance",
        Salaire: "500€/j",
        URL_offre: "https://example.com/job4",
        URL_Entreprise: "https://startupx.co",
        Description: "Besoin renfort squad product sur Node/React...",
        score_ATS: 45,
        remarque_ATS: "Type contrat Freelance non souhaité initialement.",
        _score_details: "Freelance (-10); Remote (+5)",
        data_pour_agent_redacteur: null,
        Statut: "Nouvelle",
        Source: "WTTJ",
        Date_Publication: "2023-10-22"
    },
    {
        ID_Annonce: "FT_005",
        Titre_poste: "Stagiaire Développeur Web",
        Entreprise: "Boulangerie Du Coin",
        Lieu: "Bordeaux",
        Type_contrat: "Stage",
        Salaire: "Gratification légale",
        URL_offre: "https://example.com/job5",
        URL_Entreprise: "",
        Description: "Refonte du site vitrine sous WordPress...",
        score_ATS: 20,
        remarque_ATS: "Niveau stage, trop junior.",
        _score_details: "Stage (-20); Wordpress (-5)",
        data_pour_agent_redacteur: null,
        Statut: "Nouvelle",
        Source: "FT",
        Date_Publication: "2023-10-21"
    },

    // 2. STATUT: A VÉRIFIER (3 items)
    {
        ID_Annonce: "WTTJ_006",
        Titre_poste: "Lead Dev Frontend",
        Entreprise: "ScaleUp FinTech",
        Lieu: "Paris",
        Type_contrat: "CDI",
        Salaire: "80k€+",
        URL_offre: "https://example.com/job6",
        URL_Entreprise: "https://scaleup.finance",
        Description: "Scale-up en hypercroissance, équipe de 10 devs...",
        score_ATS: 88,
        remarque_ATS: "Super opportunité, correspond au plan de carrière.",
        _score_details: "Lead (+10); Fintech (+2)",
        data_pour_agent_redacteur: JSON.stringify({
            diagnostic_gap: "Le CV met en avant React mais manque de mention sur la gestion d'équipe large (10+).",
            stratégie_adaptation: "Insister sur le mentorat fait chez l'employeur précédent.",
            mots_cles_obligatoires: ["Management", "Ceinture noire React", "Scalabilité"],
            titre_cv_recommande: "Lead Developer React / Engineering Manager"
        }),
        CV_Texte_Adapte: "Expérience significative en leadership d'équipe technique...",
        LM_Texte: "Madame, Monsieur, Fort de 10 ans d'expérience...",
        Message_Contact: "Bonjour, très intéressé par le poste de Lead Dev...",
        Statut: "A vérifier",
        Source: "WTTJ",
        Date_Publication: "2023-10-20"
    },
    {
        ID_Annonce: "FT_007",
        Titre_poste: "Développeur Vue.js Senior",
        Entreprise: "Digital Agency",
        Lieu: "Lille",
        Type_contrat: "CDI",
        Salaire: "55k€",
        URL_offre: "https://example.com/job7",
        URL_Entreprise: "https://digital-agency.fr",
        Description: "Projets variés pour grands comptes, stack Vue 3...",
        score_ATS: 72,
        remarque_ATS: "Bon match technique mais stack secondaire (Vue vs React).",
        _score_details: "Vue (+5); Senior (+5)",
        data_pour_agent_redacteur: JSON.stringify({
            diagnostic_gap: "Expérience Vue.js présente mais datée de 2021.",
            stratégie_adaptation: "Valoriser la capacité d'adaptation framework agnostique.",
            mots_cles_obligatoires: ["Vue 3", "Composition API", "Vite"],
            titre_cv_recommande: "Senior Frontend Developer (Vue/React)"
        }),
        CV_Texte_Adapte: "Expertise frontend moderne...",
        LM_Texte: "Madame, Monsieur, Ayant pratiqué Vue.js...",
        Message_Contact: "Bonjour, je souhaite postuler...",
        Statut: "A vérifier",
        Source: "FT",
        Date_Publication: "2023-10-19"
    },
    {
        ID_Annonce: "WTTJ_008",
        Titre_poste: "Product Engineer",
        Entreprise: "Alan",
        Lieu: "Paris",
        Type_contrat: "CDI",
        Salaire: "Competitive",
        URL_offre: "https://example.com/job8",
        URL_Entreprise: "https://alan.com",
        Description: "Rejoignez l'équipe santé...",
        score_ATS: 85,
        remarque_ATS: "Culture fit très important.",
        _score_details: "Product (+5); Brand (+5)",
        data_pour_agent_redacteur: JSON.stringify({
            diagnostic_gap: "Le ton du CV est trop formel pour Alan.",
            stratégie_adaptation: "Adopter un ton plus direct et 'owner'.",
            mots_cles_obligatoires: ["Ownership", "User Centric", "No-ego"],
            titre_cv_recommande: "Product Engineer"
        }),
        CV_Texte_Adapte: "Owner de mes sujets de A à Z...",
        LM_Texte: "Hello Team Alan...",
        Message_Contact: "Hello, fan de la culture Alan...",
        Statut: "A vérifier",
        Source: "WTTJ",
        Date_Publication: "2023-10-18"
    },

    // 3. STATUT: PRÊTE (3 items)
    {
        ID_Annonce: "FT_009",
        Titre_poste: "Développeur Angular",
        Entreprise: "ESN BigOne",
        Lieu: "Nantes",
        Type_contrat: "CDI",
        Salaire: "45k€",
        URL_offre: "https://example.com/job9",
        URL_Entreprise: "",
        Description: "Mission longue durée chez client bancaire...",
        score_ATS: 60,
        remarque_ATS: "Mission ESN classique.",
        _score_details: "ESN (-2); Angular (+2)",
        data_pour_agent_redacteur: null,
        Prenom_Recruteur: "Jean",
        Nom_Recruteur: "Dupont",
        Poste_Recruteur: "Talent Acquisition",
        Email_Recruteur: "j.dupont@esn-bigone.com",
        Linkedin_Recruteur: "https://linkedin.com/in/jdupont",
        CV_Doc_URL: "https://example.com/cv.pdf",
        LM_Doc_URL: "https://example.com/lm.pdf",
        Message_Contact: "Bonjour Jean, voici ma candidature...",
        Statut: "Prête",
        Source: "FT",
        Date_Publication: "2023-10-15"
    },
    {
        ID_Annonce: "WTTJ_010",
        Titre_poste: "Frontend Developer",
        Entreprise: "Qonto",
        Lieu: "Paris",
        Type_contrat: "CDI",
        Salaire: "65k€",
        URL_offre: "https://example.com/job10",
        URL_Entreprise: "https://qonto.com",
        Description: "Equipe growth, focus conversion...",
        score_ATS: 90,
        remarque_ATS: "Top tiers company.",
        _score_details: "Fintech (+5); Growth (+2)",
        data_pour_agent_redacteur: null,
        Prenom_Recruteur: "Sarah",
        Nom_Recruteur: "Connor",
        Poste_Recruteur: "HR BP",
        Email_Recruteur: "sarah@qonto.com",
        Linkedin_Recruteur: "https://linkedin.com/in/sconnor",
        CV_Doc_URL: "https://example.com/cv_qonto.pdf",
        LM_Doc_URL: "https://example.com/lm_qonto.pdf",
        Message_Contact: "Bonjour Sarah, ravie d'échanger...",
        Statut: "Prête",
        Source: "WTTJ",
        Date_Publication: "2023-10-14"
    },
    {
        ID_Annonce: "MININT_011",
        Titre_poste: "Chef de projet SI",
        Entreprise: "DINSIC",
        Lieu: "Paris",
        Type_contrat: "CDI",
        Salaire: "Selon grille",
        URL_offre: "https://example.com/job11",
        URL_Entreprise: "",
        Description: "Pilotage de projets transverses...",
        score_ATS: 70,
        remarque_ATS: "Poste fonctionnel.",
        _score_details: "Public (+2); CP (+2)",
        data_pour_agent_redacteur: null,
        Prenom_Recruteur: "Marc",
        Nom_Recruteur: "Aurel",
        Poste_Recruteur: "DSI",
        Email_Recruteur: "",
        Linkedin_Recruteur: "",
        CV_Doc_URL: "https://example.com/cv_dinsic.pdf",
        LM_Doc_URL: "https://example.com/lm_dinsic.pdf",
        Message_Contact: "",
        Statut: "Prête",
        Source: "MININT",
        Date_Publication: "2023-10-13"
    },

    // 4. STATUT: AUTRES (4 items)
    {
        ID_Annonce: "WTTJ_012",
        Titre_poste: "CTO",
        Entreprise: "SmallStartup",
        Lieu: "Paris",
        Type_contrat: "Associé",
        Salaire: "Equity",
        URL_offre: "https://example.com/job12",
        URL_Entreprise: "",
        Description: "Cherche CTO pour lancer MVP...",
        score_ATS: 50,
        remarque_ATS: "Risqué mais challengeant.",
        _score_details: "Equity only (-10)",
        data_pour_agent_redacteur: null,
        Date_Envoie: "2023-10-01",
        Statut: "Envoyée",
        Source: "WTTJ",
        Date_Publication: "2023-09-30"
    },
    {
        ID_Annonce: "FT_013",
        Titre_poste: "Développeur React Native",
        Entreprise: "AppStudio",
        Lieu: "Bordeaux",
        Type_contrat: "CDI",
        Salaire: "45k€",
        URL_offre: "https://example.com/job13",
        URL_Entreprise: "",
        Description: "Mobile first...",
        score_ATS: 68,
        remarque_ATS: "",
        _score_details: "Mobile (+5)",
        data_pour_agent_redacteur: null,
        Date_Envoie: "2023-09-25",
        Date_Entretien: "2023-10-30T14:00:00",
        Statut: "Entretien",
        Source: "FT",
        Date_Publication: "2023-09-20"
    },
    {
        ID_Annonce: "WTTJ_014",
        Titre_poste: "Senior Backend Dev",
        Entreprise: "UnicornSas",
        Lieu: "Remote",
        Type_contrat: "CDI",
        Salaire: "90k€",
        URL_offre: "https://example.com/job14",
        URL_Entreprise: "",
        Description: "Python/Go expert needed...",
        score_ATS: 95,
        remarque_ATS: "Perfect match.",
        _score_details: "Python (+5); Go (+5)",
        data_pour_agent_redacteur: null,
        Date_Envoie: "2023-09-10",
        Statut: "Offre",
        Source: "WTTJ",
        Date_Publication: "2023-09-01"
    },
    {
        ID_Annonce: "FT_015",
        Titre_poste: "Webmaster",
        Entreprise: "TPE Locale",
        Lieu: "Village",
        Type_contrat: "CDI",
        Salaire: "SMIC",
        URL_offre: "https://example.com/job15",
        URL_Entreprise: "",
        Description: "Gestion site internet...",
        score_ATS: 30,
        remarque_ATS: "Sous-qualifié.",
        _score_details: "Webmaster (-5)",
        data_pour_agent_redacteur: null,
        Statut: "Refusée",
        Source: "FT",
        Date_Publication: "2023-08-15"
    }
];
